# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e0dc09040193f551ef957f0529658d3803065e074a11692fff6a5030ef96155b1be3484423652eef6f45882e40d1efad4c50878d23c36bba6b711970e4be1d

test:
  secret_key_base: 144ef9f388a8c7164e112f4351f2ec6c6818e662c45851e269f5617daa5802316de348599df556ec538cd0240ad6a7eac594dae1401fc8352028fdd502ed5986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
